//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCelexA.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_CELEXAEntities : DbContext
    {
        public bd_CELEXAEntities()
            : base("name=bd_CELEXAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_CAT_GRUPO> TBL_CAT_GRUPO { get; set; }
        public virtual DbSet<TBL_CAT_IDIOMA> TBL_CAT_IDIOMA { get; set; }
        public virtual DbSet<TBL_CAT_NIVEL> TBL_CAT_NIVEL { get; set; }
        public virtual DbSet<TBL_OPE_ALUMNO> TBL_OPE_ALUMNO { get; set; }
        public virtual DbSet<TBL_OPE_PAGO> TBL_OPE_PAGO { get; set; }
        public virtual DbSet<TBL_OPE_PROFESOR> TBL_OPE_PROFESOR { get; set; }
        public virtual DbSet<TBL_OPE_RESULTADOS> TBL_OPE_RESULTADOS { get; set; }
        public virtual DbSet<TBL_REL_ALUMNO_PROFESOR_IDIOMA> TBL_REL_ALUMNO_PROFESOR_IDIOMA { get; set; }
    }
}
