//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCelexA.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OPE_RESULTADOS
    {
        public int Resultado_Id { get; set; }
        public Nullable<int> Resultado_ME { get; set; }
        public Nullable<int> Resultado_FE { get; set; }
        public Nullable<int> Resultado_AVG { get; set; }
        public Nullable<int> Alumno_Id { get; set; }
    
        public virtual TBL_OPE_ALUMNO TBL_OPE_ALUMNO { get; set; }
    }
}
