//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCelexA.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CAT_NIVEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CAT_NIVEL()
        {
            this.TBL_REL_ALUMNO_PROFESOR_IDIOMA = new HashSet<TBL_REL_ALUMNO_PROFESOR_IDIOMA>();
        }
    
        public int Nivel_Id { get; set; }
        public string Nivel_Grado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_REL_ALUMNO_PROFESOR_IDIOMA> TBL_REL_ALUMNO_PROFESOR_IDIOMA { get; set; }
    }
}
