//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCelexA.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_REL_ALUMNO_PROFESOR_IDIOMA
    {
        public int ID { get; set; }
        public Nullable<int> Alumno_Id { get; set; }
        public Nullable<int> Profesor_Id { get; set; }
        public Nullable<int> Idioma_Id { get; set; }
        public Nullable<int> Grupo_Id { get; set; }
        public Nullable<int> Nivel_Id { get; set; }
    
        public virtual TBL_CAT_GRUPO TBL_CAT_GRUPO { get; set; }
        public virtual TBL_CAT_IDIOMA TBL_CAT_IDIOMA { get; set; }
        public virtual TBL_CAT_NIVEL TBL_CAT_NIVEL { get; set; }
        public virtual TBL_OPE_ALUMNO TBL_OPE_ALUMNO { get; set; }
        public virtual TBL_OPE_PROFESOR TBL_OPE_PROFESOR { get; set; }
    }
}
