//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCelexA.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OPE_PROFESOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_OPE_PROFESOR()
        {
            this.TBL_REL_ALUMNO_PROFESOR_IDIOMA = new HashSet<TBL_REL_ALUMNO_PROFESOR_IDIOMA>();
        }
    
        public int Profesor_Id { get; set; }
        public string Profesor_Email { get; set; }
        public string Profesor_Pass { get; set; }
        public string Profesor_Nombre { get; set; }
        public string Profesor_AP { get; set; }
        public string Profesor_AM { get; set; }
        public Nullable<System.DateTime> Profesor_FechaIngreso { get; set; }
        public Nullable<bool> Profesor_Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_REL_ALUMNO_PROFESOR_IDIOMA> TBL_REL_ALUMNO_PROFESOR_IDIOMA { get; set; }
    }
}
