//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCelexA.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OPE_ALUMNO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_OPE_ALUMNO()
        {
            this.TBL_OPE_PAGO = new HashSet<TBL_OPE_PAGO>();
            this.TBL_REL_ALUMNO_PROFESOR_IDIOMA = new HashSet<TBL_REL_ALUMNO_PROFESOR_IDIOMA>();
            this.TBL_OPE_RESULTADOS = new HashSet<TBL_OPE_RESULTADOS>();
        }
    
        public int Alumno_Id { get; set; }
        public string Alumno_Email { get; set; }
        public string Alumno_Pass { get; set; }
        public string Alumno_Nombre { get; set; }
        public string Alumno_AP { get; set; }
        public string Alumno_AM { get; set; }
        public Nullable<System.DateTime> Alumno_FehcaIngreso { get; set; }
        public Nullable<bool> Alumno_Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_OPE_PAGO> TBL_OPE_PAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_REL_ALUMNO_PROFESOR_IDIOMA> TBL_REL_ALUMNO_PROFESOR_IDIOMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_OPE_RESULTADOS> TBL_OPE_RESULTADOS { get; set; }
    }
}
