//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCelexA.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OPE_PAGO
    {
        public int Pago_Id { get; set; }
        public string Pago_Referencia { get; set; }
        public Nullable<int> Pago_Monto { get; set; }
        public string Pago_Vaucher_ruta { get; set; }
        public Nullable<int> Alumno_Id { get; set; }
    
        public virtual TBL_OPE_ALUMNO TBL_OPE_ALUMNO { get; set; }
    }
}
